CREATE DATABASE OKUL_KUTUPHANESI2

USE OKUL_KUTUPHANESI2;


CREATE TABLE UYELER(
	UYE_NO INT IDENTITY(1,1) NOT NULL,
	UYE_ADI VARCHAR(20),
	UYE_SOYADI VARCHAR(20),
	CINSIYET VARCHAR(20),
	TELEFON VARCHAR(15),
	EPOSTA VARCHAR(40),
	ADRES_NO INT,
	PRIMARY KEY("UYE_NO")
);
CREATE TABLE ADRESLER(
	ADRES_NO INT IDENTITY(1,1),
	CADDE VARCHAR(20),
	MAHALLE VARCHAR(20),
	BINA_NO VARCHAR(20),
	SEHIR VARCHAR(20),
	POSTA_KODU INT,
	ULKE VARCHAR(20),
	PRIMARY KEY ("ADRES_NO")
);
	ALTER TABLE UYELER ADD CONSTRAINT "ADRESLER_UYELER" 
	FOREIGN KEY (ADRES_NO) REFERENCES ADRESLER(ADRES_NO);

CREATE TABLE EMANET(
	EMANET_NO INT IDENTITY(1,1),
	ISBN VARCHAR(20) NOT NULL,
	UYE_NO INT NOT NULL,
	KUTUPHANE_NO INT NOT NULL,
	EMANET_TARIHI DATETIME,
	TESLIM_TARIHI DATETIME,
	PRIMARY KEY ("EMANET_NO")
);
	ALTER TABLE EMANET ADD CONSTRAINT "UYELER_EMANET"
	FOREIGN KEY (UYE_NO) REFERENCES UYELER(UYE_NO);
	
CREATE TABLE KITAPLAR(
	ISBN VARCHAR(20),
	KITAP_ADI VARCHAR(20),
	YAYIN_TARIHI VARCHAR(20),
	S_SAYISI INT,
	PRIMARY KEY ("ISBN")
);
	ALTER TABLE EMANET ADD CONSTRAINT "EMANET_KITAPLAR"
	FOREIGN KEY (ISBN) REFERENCES KITAPLAR(ISBN);

CREATE TABLE YAZARLAR(
	YAZAR_NO INT IDENTITY(1,1),
	YAZAR_ADI VARCHAR(20),
	YAZAR_SOYADI VARCHAR(20),
	PRIMARY KEY ("YAZAR_NO")
);

CREATE TABLE KATEGORILER(
	KATEGORI_NO INT IDENTITY(1,1),
	KATEGORI_ADI VARCHAR(20),
	PRIMARY KEY ("KATEGORI_NO")
);

CREATE TABLE KUTUPHANE(
	KUTUPHANE_NO INT IDENTITY(1,1),
	KUTUPHANE_ADI VARCHAR(20),
	ACIKLAMA VARCHAR(20),
	ADRES_NO INT,
	PRIMARY KEY ("KUTUPHANE_NO")
);
	ALTER TABLE KUTUPHANE ADD CONSTRAINT "KUTUPHANE_ADRESLER"
	FOREIGN KEY (ADRES_NO) REFERENCES ADRESLER(ADRES_NO);

CREATE TABLE KITAP_KUTUPHANE(
	KUTUPHANE_NO INT NOT NULL,
	ISBN VARCHAR(20) NOT NULL,
	MIKTAR INT,
	CONSTRAINT "KITAP_KUTUPHANE_PK" PRIMARY KEY ("KUTUPHANE_NO", "ISBN"),
	CONSTRAINT "KITAP_KUTUPHANE_FK" FOREIGN KEY ("KUTUPHANE_NO") REFERENCES KUTUPHANE(KUTUPHANE_NO)
);
	ALTER TABLE KITAP_KUTUPHANE ADD CONSTRAINT "KITAP_KUTUPHANE_KITAPLAR_FK" FOREIGN KEY ("ISBN") REFERENCES KITAPLAR(ISBN);

CREATE TABLE KITAP_KATEGORI(
	ISBN VARCHAR(20) NOT NULL,
	KATEGORI_NO INT NOT NULL,
	CONSTRAINT "KITAP_KATEGORI_PK" PRIMARY KEY ("KATEGORI_NO", "ISBN"),
	CONSTRAINT "KITAP_KATEGORI_FK" FOREIGN KEY ("KATEGORI_NO") REFERENCES KATEGORILER(KATEGORI_NO)
);
	ALTER TABLE KITAP_KATEGORI ADD CONSTRAINT "KITAP_KATEGORI_KITAPLAR_FK" FOREIGN KEY ("ISBN") REFERENCES KITAPLAR(ISBN);

CREATE TABLE KITAP_YAZAR(
	ISBN VARCHAR(20) NOT NULL,
	YAZAR_NO INT NOT NULL,
	CONSTRAINT "KITAP_YAZAR_PK" PRIMARY KEY ("YAZAR_NO", "ISBN"),
	CONSTRAINT "KITAP_YAZAR_FK" FOREIGN KEY ("YAZAR_NO") REFERENCES YAZARLAR(YAZAR_NO)
);
	ALTER TABLE KITAP_YAZAR ADD CONSTRAINT "KITAP_YAZAR_KITAPLAR_FK" FOREIGN KEY ("ISBN") REFERENCES KITAPLAR(ISBN);

	ALTER TABLE EMANET ADD CONSTRAINT "KUTUPHANE_EMANET"
	FOREIGN KEY (KUTUPHANE_NO) REFERENCES KUTUPHANE(KUTUPHANE_NO);

	USE OKUL_KUTUPHANESI2
	SELECT * FROM UYELER

	INSERT INTO UYELER VALUES('Ayþe', 'Kara', 'K', '3561234556', 'aa@mail.com', NULL);
	INSERT INTO UYELER VALUES('Ali', 'Uçar', 'E', '3562345667', 'au@abc.com', NULL);

	SELECT*FROM ADRESLER
	INSERT INTO ADRESLER VALUES('Orhangazi', 'Esentepe', 5, 'Tokat', '60100', 'Türkiye' );
	INSERT INTO ADRESLER VALUES('Atatürk', 'Barbaros', 142, 'Ýstanbul', '34200', 'Türkiye' );
	INSERT INTO ADRESLER VALUES('Belsin', 'Týnaztepe', 3049, 'Kayseri', '38000', 'Türkiye' );
	DELETE FROM ADRESLER WHERE ADRES_NO=4

	UPDATE UYELER
	SET EPOSTA='au@mail.com' 
	WHERE UYE_NO=7;


	

	 






 
